// <auto-generated />
using System;
using CapstoneProjectFashionHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProjectFashionHub.Migrations
{
    [DbContext(typeof(AplikasiDbContext))]
    partial class AplikasiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProjectFashionHub.Models.ContactForm", b =>
                {
                    b.Property<int>("IdKontak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKontak"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKontak");

                    b.ToTable("ContactForm");
                });

            modelBuilder.Entity("CapstoneProjectFashionHub.Models.Kategori", b =>
                {
                    b.Property<int>("ID_Kategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Kategori"));

                    b.Property<string>("Nama_Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Kategori");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("CapstoneProjectFashionHub.Models.Layanan", b =>
                {
                    b.Property<int>("ID_Layanan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Layanan"));

                    b.Property<double?>("Biaya")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama_Layanan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Layanan");

                    b.ToTable("Layanan");
                });
#pragma warning restore 612, 618
        }
    }
}
